# Generated by Django 5.1.3 on 2024-11-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(error_messages={'blank': 'The group cannot be empty', 'does_not_exist': 'The group does not exist', 'invalid': 'Invalid value for the group', 'null': 'The group cannot be empty', 'required': 'The group is required'}, on_delete=django.db.models.deletion.CASCADE, related_name='task_group', to='task.group'),
        ),
    ]
