# Generated by Django 5.1.3 on 2024-12-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(error_messages={'blank': 'The title cannot be empty', 'invalid': 'Invalid value for the title', 'max_length': 'The title should not exceed 50 characters', 'null': 'The title cannot be empty', 'required': 'The title is required', 'unique': 'The category is not unique'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(error_messages={'blank': 'The title cannot be empty', 'invalid': 'Invalid value for the title', 'max_length': 'The title should not exceed 50 characters', 'null': 'The title cannot be empty', 'required': 'The title is required', 'unique': 'The title is not unique'}, max_length=50, unique=True),
        ),
    ]
