# Generated by Django 5.1.3 on 2024-12-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(error_messages={'blank': 'The student ID cannot be empty', 'invalid': 'Invalid value for the student ID', 'max_length': 'The student ID should not exceed 10 characters', 'null': 'The student ID cannot be empty', 'required': 'The student ID is required.', 'unique': 'The student ID is not unique.'}, max_length=10, unique=True),
        ),
    ]
